//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.08 at 10:53:55 PM IST 
//


package com.shopdirect.ws.xsd.accountstatus;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for accountStatusType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="accountStatusType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="com.lsdg.ws.AccountStatus.AccountStatusObjects.AccountStatusType" type="{http://ws.shopdirect.com/xsd/AccountStatus}com.lsdg.ws.AccountStatus.AccountStatusObjects.AccountStatusType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "accountStatusType", propOrder = {
    "comLsdgWsAccountStatusAccountStatusObjectsAccountStatusType"
})
public class AccountStatusType {

    @XmlElement(name = "com.lsdg.ws.AccountStatus.AccountStatusObjects.AccountStatusType", required = true)
    protected List<ComLsdgWsAccountStatusAccountStatusObjectsAccountStatusType> comLsdgWsAccountStatusAccountStatusObjectsAccountStatusType;

    /**
     * Gets the value of the comLsdgWsAccountStatusAccountStatusObjectsAccountStatusType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the comLsdgWsAccountStatusAccountStatusObjectsAccountStatusType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getComLsdgWsAccountStatusAccountStatusObjectsAccountStatusType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ComLsdgWsAccountStatusAccountStatusObjectsAccountStatusType }
     * 
     * 
     */
    public List<ComLsdgWsAccountStatusAccountStatusObjectsAccountStatusType> getComLsdgWsAccountStatusAccountStatusObjectsAccountStatusType() {
        if (comLsdgWsAccountStatusAccountStatusObjectsAccountStatusType == null) {
            comLsdgWsAccountStatusAccountStatusObjectsAccountStatusType = new ArrayList<ComLsdgWsAccountStatusAccountStatusObjectsAccountStatusType>();
        }
        return this.comLsdgWsAccountStatusAccountStatusObjectsAccountStatusType;
    }

}
