//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.08 at 10:53:55 PM IST 
//


package com.shopdirect.ws.xsd.accountstatus;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for customerDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="customerDetail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="accountNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="chordiantId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="accountStatusType" type="{http://ws.shopdirect.com/xsd/AccountStatus}accountStatusType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "customerDetail", propOrder = {
    "accountNumber",
    "chordiantId",
    "accountStatusType"
})
public class CustomerDetail {

    @XmlElement(required = true)
    protected String accountNumber;
    @XmlElement(required = true)
    protected String chordiantId;
    protected AccountStatusType accountStatusType;

    /**
     * Gets the value of the accountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * Sets the value of the accountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNumber(String value) {
        this.accountNumber = value;
    }

    /**
     * Gets the value of the chordiantId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChordiantId() {
        return chordiantId;
    }

    /**
     * Sets the value of the chordiantId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChordiantId(String value) {
        this.chordiantId = value;
    }

    /**
     * Gets the value of the accountStatusType property.
     * 
     * @return
     *     possible object is
     *     {@link AccountStatusType }
     *     
     */
    public AccountStatusType getAccountStatusType() {
        return accountStatusType;
    }

    /**
     * Sets the value of the accountStatusType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountStatusType }
     *     
     */
    public void setAccountStatusType(AccountStatusType value) {
        this.accountStatusType = value;
    }

}
