//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.08 at 10:53:55 PM IST 
//


package com.shopdirect.ws.xsd.accountstatus;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for customerAccountStatus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="customerAccountStatus">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="accountNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="custStatusDetails" type="{http://ws.shopdirect.com/xsd/AccountStatus}custStatusDetails" minOccurs="0"/>
 *         &lt;element name="accountStatusRecommendations" type="{http://ws.shopdirect.com/xsd/AccountStatus}accountStatusRecommendations" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "customerAccountStatus", propOrder = {
    "accountNumber",
    "custStatusDetails",
    "accountStatusRecommendations"
})
public class CustomerAccountStatus {

    @XmlElement(required = true)
    protected String accountNumber;
    protected CustStatusDetails custStatusDetails;
    protected AccountStatusRecommendations accountStatusRecommendations;

    /**
     * Gets the value of the accountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * Sets the value of the accountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNumber(String value) {
        this.accountNumber = value;
    }

    /**
     * Gets the value of the custStatusDetails property.
     * 
     * @return
     *     possible object is
     *     {@link CustStatusDetails }
     *     
     */
    public CustStatusDetails getCustStatusDetails() {
        return custStatusDetails;
    }

    /**
     * Sets the value of the custStatusDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustStatusDetails }
     *     
     */
    public void setCustStatusDetails(CustStatusDetails value) {
        this.custStatusDetails = value;
    }

    /**
     * Gets the value of the accountStatusRecommendations property.
     * 
     * @return
     *     possible object is
     *     {@link AccountStatusRecommendations }
     *     
     */
    public AccountStatusRecommendations getAccountStatusRecommendations() {
        return accountStatusRecommendations;
    }

    /**
     * Sets the value of the accountStatusRecommendations property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountStatusRecommendations }
     *     
     */
    public void setAccountStatusRecommendations(AccountStatusRecommendations value) {
        this.accountStatusRecommendations = value;
    }

}
